Sources/XCHammer/XcodeTarget.swift
sample/UrlGet/UrlGet.xcodeproj/project.pbxproj
sample/UrlGet/ios-app/BUILD
sample/UrlGet/ios-app/HeaderLib/BUILD
sample/UrlGet/ios-app/HeaderLib/HeaderLib.cpp

A "Header Library", a library consisting of only headers.
Under Xcode, there is no linkable artifact produced by the target,
since there is nothing to compile.
This patch prevents from linking them.

Don't attempt to link "Header libraries"

---

Sources/XCHammer/Generator.swift

In order to build XCHammer with newer dependencies, the use of the deprecated `&&&` operator needs to be replaced. See https://github.com/antitypical/Result/pull/220
This `reduce()` appears to have not been working, because it wasn't modifying the `inout` state.
EDIT: It seems that `flatMap()` is the correct operation here, not `fanout()` as I originally had.

Replace use of &&& with flatMap()

---

Sources/XCHammer/XcodeTarget.swift
sample/UrlGet/UrlGet.xcodeproj/project.pbxproj

Simulator builds shouldn't be entitled if there is no entitlements
available. In some test configurations, entitlements will not be present
at the testing level.

Prevent invalid simulator entitlement

---

Package.resolved
Package.swift

XcodeGen 1.11.2 is needed to build (for release) with Swift 4.2 (Xcode 10). The fix is here: https://github.com/yonaskolb/XcodeGen/pull/404

Update XcodeGen dependency to 1.11.2

---

Makefile

These files need to be adjacent to the XCHammer binary. XCHammer and
dependencies use NSBundle to load them in such a way.

Fix Xcode GUI experience

---

IntegrationTests/run_tests.sh
Makefile
Sources/XCHammer/main.swift

This change makes XCHammer generate Bazel targets by default, without needing to pass `--generate_bazel_targets`. A quick look at Commandant shows that this can be disabled with `--no-generate_bazel_targets`.

Generate bazel targets by default

---

Sources/XCHammer/ProjectWriter.swift
Sources/XCHammer/XcodeTarget.swift
XCHammerAssets/Hammer.bzl
sample/UrlGet/UrlGet.xcodeproj/XCHammerAssets/BUILD
sample/UrlGet/UrlGet.xcodeproj/XCHammerAssets/bazel_build_settings.py
sample/UrlGet/UrlGet.xcodeproj/XCHammerAssets/updateXcodeProj.sh
sample/UrlGet/UrlGet.xcodeproj/project.pbxproj
sample/UrlGet/UrlGet.xcodeproj/xcshareddata/xcschemes/UITests-Bazel.xcscheme
sample/UrlGet/UrlGet.xcodeproj/xcshareddata/xcschemes/UITests.xcscheme
sample/UrlGet/UrlGet.xcodeproj/xcshareddata/xcschemes/UnitTests-Bazel.xcscheme
sample/UrlGet/UrlGet.xcodeproj/xcshareddata/xcschemes/UnitTests.xcscheme
sample/UrlGet/UrlGet.xcodeproj/xcshareddata/xcschemes/UnitTestsWithHost-Bazel.xcscheme
sample/UrlGet/UrlGet.xcodeproj/xcshareddata/xcschemes/UnitTestsWithHost.xcscheme
sample/UrlGet/UrlGet.xcodeproj/xcshareddata/xcschemes/ios-app-Bazel.xcscheme
sample/UrlGet/UrlGet.xcodeproj/xcshareddata/xcschemes/ios-app.xcscheme
sample/UrlGet/UrlGet.xcodeproj/xcshareddata/xcschemes/share-extension-Bazel.xcscheme
sample/UrlGet/ios-app/BUILD

This commit allows source files to be missing at generation time.
This fixes an aspect of #46 where generation fails where files are missing.

Allow source files to be missing at gen time

---

IntegrationTests/run_tests.sh
Makefile

The hacky Makefile wasn't building aspects before running tests. Resolve
packages
We need to get rid of this Makefile and SPM - until XCHammer can build
XCHammer Xcode projects it's required.

Fix aspect error on CI

---

Docs/XCHammerFAQ.md
Sources/XCHammer/Generator.swift

This commit removes the `if Xcode` hack in Generator.swift. This isn't
needed anymore and causes issues. Additionally clarify Xcode usage in
the Docs.

Remove `if Xcode` defines, improve docs

---

Sources/XCHammer/XcodeTarget.swift

This change is required to support building targets that are built from rules_swift's `swift_library` rule.

Update extractBuiltProductName to handle static libraries

---

Sources/XCHammer/XCHammerGenerateOptions.swift
Sources/XCHammer/XcodeTargetMap.swift

This is a fix to how XCHammer handles project paths for the very simple, new user initial use case.
With this change, either of these configs now work:
```yml
projects:
HammerLyft: {}
```
```yml
projects:
HammerLyft:
paths:
- "**"
```
The change is twofold:
1. Make `**` the default path set if one is not provided
2. Handle `**` as a recursive glob
For the second part, previously, recursive globs had to be prefixed by a `/`.

Improve handling of project paths

---

Sources/XCHammer/XcodeTarget.swift

This fixes an issue with generating the path to `bazel_build.py`. The error message:
```
~/Library/Developer/Xcode/DerivedData/HammerLyft-apdrvgdqsckgxbeluodmnicxohsd/Build/Intermediates.noindex/HammerLyft.build/Debug-iphonesimulator/ArchitectureCore-Bazel.build/Script-SSBP_7741122292.sh: line 3: ./bazel_build.py: No such file or directory
```
The fix is to use `ProcessInfo.processInfo.arguments` instead of `CommandLine.arguments` because the former has the full path to `XCHammer` while the latter has just whatever was given on the command line, which will often be just `"XCHammer"`.

Resolve full path of XCHammer for bazel_build.py

---

.travis.yml
Makefile
sample/Frankenstein/.bazelrc
sample/Frankenstein/.gitignore
sample/Frankenstein/BUILD
sample/Frankenstein/Info.plist
sample/Frankenstein/Makefile
sample/Frankenstein/Pods.WORKSPACE
sample/Frankenstein/Vendor/PodSpecs/boost-for-react-native-1.63.0-0/boost-for-react-native.podspec
sample/Frankenstein/Vendor/PodSpecs/glog-0.3.4/ios-configure-glog.sh
sample/Frankenstein/Vendor/PodSpecs/react-0.57/third-party-podspecs/DoubleConversion.podspec
sample/Frankenstein/Vendor/PodSpecs/react-0.57/third-party-podspecs/Folly.podspec
sample/Frankenstein/Vendor/PodSpecs/react-0.57/third-party-podspecs/glog.podspec
sample/Frankenstein/WORKSPACE
sample/Frankenstein/XCHammer.yaml
sample/Frankenstein/main.m
sample/Frankenstein/tools/bazelwrapper

This commit adds another example of a project containing RN and all of
it's trans deps.
On the CI, we run XCHammer to just build the Xcode project as a perf
test of this condition.
Now that PodToBUILD can build ReactNative, this is easy to setup. Future
work will clean this up when we add support for external in P2B
On a maxed out 2.9 GHz Intel Core i7 MBP
```
XCHammer: ** Completed xcode_gen in 378.3899s
XCHammer: ** Completed make_schemes in 0.0283s
XCHammer: ** Completed generate_project in 380.5344s
```
This is a highly optimized case in XCHammer logic ( only 2s here ) and
exemplifies the XcodeGen issue

Perf tests: ReactNative Bazel C++ example

---

Sources/XCHammer/XcodeTarget.swift

`XcodeTarget.transitiveTargets()` traverses the dependency, and builds an array result using `flatMap`. This wasn't showing up in traces of a small project with a smaller dependency graph, but in larger projects this hits some allocation slow paths in swift (`swift_slowAlloc`).
This changes the graph traversal to be _iterative_, and brings big performance gains. Here are before and after samples:

Improve performance of XcodeTarget.transitiveTargets()

---

Makefile

This is a change to enable debugging via Xcode. TulsiGenerator accesses its `WORKSPACE` file, and probably more, from its bundle. However the `ditto` commands in the `Makefile` don't copy to the correct destination. This change copies the contents of `tulsi-aspects` into `TulsiGenerator.framework`, which in turn enables debugging via Xcode.

Copy tulsi-aspects to TulsiGenerator.framework

---

Sources/XCHammer/XcodeTarget.swift

We left print statments that print confusing messages that product types
aren't supported.

Remove debugging code

---

.gitignore
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/UITests-Bazel.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/UITests.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/UnitTests-Bazel.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/UnitTests.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/UnitTestsWithHost-Bazel.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/UnitTestsWithHost.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/ios-app-Bazel.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/ios-app.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/share-extension-Bazel.xcscheme
Makefile
Sources/XCHammer/Generator.swift
Sources/XCHammer/XcodeTarget.swift
sample/WorkspaceSource/.gitignore
sample/WorkspaceSource/BUILD
sample/WorkspaceSource/Info.plist
sample/WorkspaceSource/WORKSPACE
sample/WorkspaceSource/XCHammer.yaml
sample/WorkspaceSource/main.m
sample/WorkspaceSource/tools/bazelwrapper
sample/WorkspaceSource/workspace.bzl

This commit implements repository rule in XCHammer. It patches outputs
to `external` and finally, symlinks the canonical `external` directory
into the workspace. This ensures that the feature is portable, and
points to the canonical repostories inside of Bazel, rather than the
transient ones.
Fixes #11

Workspace rules and sample Pass 1

---

.gitignore
Makefile
Sources/XCHammer/XcodeTarget.swift
XCHammer.yaml

This commit adds the ability to build XCHammer's Xcode project with
XCHammer.
Additionally change `make workspace` to use this instead of SPM.
Incrmental builds aren't 100% out of the box, but we should add that to
Bazel and additionally support building the XCHammer Xcode project with
XCHammer.
The legacy generation command is left until incremental builds are
working.
Known issues with Swift and XCHammer:
- includes in external
- module_name propagation
- `BUILD` file naming edge cases in resources

Generate XCHammer .xcodeproj with XCHammer

---

Sources/XCHammer/Generator.swift
sample/UrlGet/XCHammer.yaml

The original XCHammer logic was very specific, and generated schemes for
Tests, and Applications. This commit generates schemes for all specified
targets.
Fixes #69

Include Xcode schemes for specified labels

---

Sources/XCHammer/Generator.swift
Sources/XCHammer/XCHammerAsset.swift
Sources/XCHammer/XcodeTarget.swift
XCHammerAssets/Stub.swift

- Adds new asset (Stub.swift)
- Should apply only to targets with swift dependencies
- Fixes swift sample project (Tailor)

Use Swift stub file for targets with zero files and swift dependencies

---

Sources/XCHammer/Generator.swift
Sources/XCHammer/XCHammerConfig.swift
Sources/XCHammer/XCHammerGenerateOptions.swift
Sources/XCHammer/XcodeTarget.swift
Sources/XCHammer/XcodeTargetMap.swift
Sources/XCHammer/main.swift

This commit makes it easier to configure larger XCHammer workspaces.
When a project get's too large, it slows down the users computer for
many reasons. Indexing and project generation times are slower due to
the size of the Xcode project.
This commit adds a few abilities to make Xcode projects with better
experiences:
`generateTransitiveXcodeTargets` - by default, XCHammer includes all
transitive Xcode targets. If this is disabled, it only generates Xcode
Targets specified in the config file.
`generateXcodeSchemes` - enable to generation of Xcode schemes.
By default, this is enabled.
In the new `focus` workspace, it builds exclusively with Bazel.
This gives it faster build times, and better cachability. Semantic
editor features still work, as all header search paths are propagated. …

[Focus] Xcode target granuarilty features

---

Docs/XCHammerFAQ.md
Makefile
README.md

Currently the supported build system of XCHammer is `make`. There are a
few blockers to using Bazel for XCHammer:
- XCHammer assets don't load correctly.
- Incremental builds don't work.
- Test coverage / move to Bazel build in Pinterest.
- It should generate a working project
Additionally, remove advice suggesting to use Bazel from the `README`.

Clarify supported XCHammer build system

---

WORKSPACE
sample/Tailor/WORKSPACE
sample/WorkspaceSource/WORKSPACE

Use master `rules_swift` (as of today). The last release tag is almost 3 months old.
Of note, rules_swift has since added support to enable batch mode by default for Xcode 10. There have been recent discussions about incremental builds for xchammer, but with batch mode enabled, a change to a `Sources/***.swift` takes about ~8-9s to compile on my machine.

Use point in time master for rules_swift

---

Sources/XCHammer/XCBuildSettings.swift
Sources/XCHammer/XcodeTarget.swift

Previously, we used a combination of `SettingsPresets` _and_ `xcconfig` to configure the Xcode build settings. With the recent change of just supporting xcconfigs, it wasn't possible to customize `OTHER_CFLAGS` in a way that would work without generated `Diags.bzl` files. This is useful for making custom `xcconfigs` and passing in `HAMMER_DIAGNOSTIC_FLAGS`
Lastly, it enables us to update XCHammer without reverting the `SettingsPresest` commit.

Export filtered diagnostic flags

---

IntegrationTests/Goldmaster/SnapshotMe.xcodeproj/project.pbxproj
IntegrationTests/Goldmaster/SnapshotMe.xcodeproj/xcshareddata/xcschemes/UnitTests-Bazel.xcscheme
IntegrationTests/Goldmaster/SnapshotMe.xcodeproj/xcshareddata/xcschemes/UnitTests.xcscheme
IntegrationTests/Goldmaster/SnapshotMe.xcodeproj/xcshareddata/xcschemes/ios-app-Bazel.xcscheme
IntegrationTests/Goldmaster/SnapshotMe.xcodeproj/xcshareddata/xcschemes/ios-app.xcscheme
IntegrationTests/Goldmaster/Tailor.xcodeproj/project.pbxproj
IntegrationTests/Goldmaster/Tailor.xcodeproj/xcshareddata/xcschemes/ios-app-Bazel.xcscheme
IntegrationTests/Goldmaster/Tailor.xcodeproj/xcshareddata/xcschemes/ios-app.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/project.pbxproj
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/UITests-Bazel.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/UITests.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/UnitTests-Bazel.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/UnitTests.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/UnitTestsWithHost-Bazel.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/UnitTestsWithHost.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/ios-app-Bazel.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/ios-app-bin-ios-12.0-Bazel.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/ios-app-bin-ios-12.0.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/ios-app.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/share-extension-Bazel.xcscheme
IntegrationTests/Goldmaster/UrlGet.xcodeproj/xcshareddata/xcschemes/share-extension.xcscheme
IntegrationTests/Goldmaster/WorkspaceSource.xcodeproj/project.pbxproj
IntegrationTests/Goldmaster/WorkspaceSource.xcodeproj/xcshareddata/xcschemes/ios-app.xcscheme
sample/Tailor/AppDelegate.swift
sample/Tailor/BUILD
sample/Tailor/Tailor.swift
sample/Tailor/XCHammer.yaml

This commit adds an example to Tailor to exemplify a basic dependency on
a `swift_library`.
More minimal examples of `swift_library` will be added to `Tailor` to
validate they work correctly

Swift dependency example

---

.travis.yml
Makefile

This improvment should speed up local builds, testing, and travis CI.
It uses travi's caching to load the cache directory across builds too.

Enable bazel remote disk caching

---

Sources/XCHammer/XcodeTarget.swift
sample/Tailor/BUILD

- Explicitly define logic for other means of determining the swift version
- Update sample project to specify swiftcopt `-swift-version 4.2`

Extract Swift version from copts

---

Makefile

The `swift package generate-xcodeproj` command runs in parallel with the `eval` command which makes `eval` command fails when runs `make workspace` in the first time after cloning the repo.
You can reproduce the error by removing the Xcode project and then run `make workspace`.

Fix error: 'XCHammer.xcodeproj/' does not exist

---

Sources/XCHammer/XCHammerConfig.swift

By my interpretation, the documentation for `buildBazelOptions` and `buildBazelStartupOptions` are reversed. Specifically, `buildBazelStartupOptions` referred to "Bazel build invocation" and `buildBazelOptions` referred just to "Bazel invocation".
This change is an attempt to try to make the distinction between the two configs more clear.

Correct XCHammer config bazel options docstrings

---

Sources/XCHammer/Generator.swift
Sources/XCHammer/XCHammerConfig.swift
Sources/XCHammer/XcodeScheme.swift
sample/SnapshotMe/XCHammer.yaml
sample/UrlGet/XCHammer.yaml

This PR adopts a subset of XcodeGen's Target Scheme. Mainly, it allows
people to select scripts to run during schemes.
The TargetSchemes are identical and shared across Bazel / Xcode targets
For now, it seems OK to have this as there are no idioms in Bazel to
achieve the same result.

Adopt subset of XcodeGen.TargetScheme

---

BUILD.bazel
Makefile
Sources/XCHammer/XcodeScheme.swift
Sources/XCHammer/main.swift
XCHammer.yaml
tools/xchammerconfig.bzl

This patch makes it possible to setup Xcode projects as rules inside of
Bazel through a DSL.
Going down the path of user provided runscripts complicates the painful
YAML XCHammerConfig.
Open questions about this include:
- Overall E2E perf impact
- How to automatically build the DSL from XCHammer directly.
Right now, this is just experimental and those questions should be
resolved in the future.

Experimental Xcode project Skylark DSL

---

Info.plist

Probably copied from an Info.plist from an iOS app.

Remove iOS specific keys from Info.plist

---

tools/instrumentation_helpers/README.md
tools/instrumentation_helpers/instrumentor.py
tools/instrumentation_helpers/statsd_post_generate_action.py

This PR adds the ability to differentiate between Xcode targets e.g.
`PinterestDevelopment`
and
`PinterestDevelopment-Bazel`
Additionally, write info along with `xchammer.generate` and
`xchammer.build` to statsd.

Add target and system info to statsd events

---

Makefile
Package.resolved
Package.swift
Sources/XCHammer/TulsiRuleEntryMapExtractor.swift
WORKSPACE
export_tulsi_aspect_dir.sh
sample/Frankenstein/tools/bazelwrapper
sample/SnapshotMe/tools/bazelwrapper
sample/Tailor/tools/bazelwrapper
sample/UrlGet/Vendor/rules_pods/tools/bazelwrapper
sample/UrlGet/WORKSPACE
sample/UrlGet/tools/bazelwrapper
sample/WorkspaceSource/tools/bazelwrapper
third_party/repositories.bzl
tools/bazelwrapper

This commit includes several changes for Bazel 0.21.0, including:
- Bump XCHammer to latest rules_apple, Tulsi
- Rewrite export script to use bazel ( Xcode project is gone )
- Fix TulsiGenerator update errors
- Bump Tulsi for Swift 4.2 fixes
- Update UrlGet rules_apple, test runners
- Update all bazelwrappers to 0.21.0

Update to Bazel 0.21.0

---

Makefile
export_tulsi_aspect_dir.sh
sample/Frankenstein/WORKSPACE

A few quick fixes to issues found in SPM builds. In Bazel `0.21`, there is a `glob *` added, which picks up a circular symlink which _may_ exist in samples.

Fix SPM build issues

---

Sources/XCHammer/Generator.swift

This is useful to differentiate in builds when the user is performing a
Profile action, as it sets the `$CONFIGURATION` variable within Xcode.

Add explicit config type for profile

---

Makefile
Sources/XCHammer/XCBuildSettings.swift
Sources/XCHammer/XcodeTarget.swift
Sources/XCHammer/XcodeTargetMap.swift
sample/SnapshotMe/WORKSPACE
sample/SnapshotMe/ios-app/BUILD
sample/SnapshotMe/tools/bazelwrapper
sample/WorkspaceSource/WORKSPACE
third_party/repositories.bzl

This PR gets swift programs ( and XCHammer ) building with Xcode to fix
indexing and semantic editor features.
It uses Bazel specified module maps, and fully uses Xcode's build system
to build the swift modules. This approach is as "vanilla" as possible:
it doesn't use Bazel to build anything, and Bazel builds its own swift
modules.
Includes:
- Tulsi bump ( propagate module name for swift fix )
- Using objc library, for deps in repositories.bzl as cc_library is busted
- Better support for bundled sources
- Include resolution to _tulsi_includes
- Propagation of swift_c_module
Known issues, TODOS, and FIXMES:
- swift module dependencies are built with Target deps ATM, which is
incompatible with mutli project mode.
- It passes the module name to the compiler from Xcode. This will
probably …

Pure Xcode Swift support

---

Sources/XCHammer/Generator.swift

This was broken and didn't actually do anything anyways.

Remove unneeded version mismatch warning

---

XCHammerAssets/codesigner.sh

Previously, we only signed frameworks. This is needed for running test
bundles on devices from Xcode

Add codepath to sign plugins

---

Sources/XCHammer/ProjectWriter.swift

Add fine grained insturmentation to split out the difference between
generating an xcproj and writing it to disk.
This allows us to visualize the difference in the 2 phases

Add more instrumentation around gen

---

Makefile

- When running `make install`, a directory will be created at `/usr/local/bin/xchammer.app` instead of moving the contents of `xchammer.app` to `/usr/local/bin`
- When running `make uninstall`, the directory `/usr/local/bin/xchammer.app` will be removed instead of the contents of `/usr/local/bin`
- A symlink from `/usr/local/bin/xchammer.app/Contents/MacOS/xchammer` to `/usr/local/bin/xchammer` will be created so that `xchammer` commands can be run from Terminal
Fixes #76 
Fixes #170

Prevent `make install` from polluting /usr/local/bin

---

Sources/XCHammer/ProjectWriter.swift

We had the new build system disabled for a reason that has been resolved, let’s enable
It again

Enable new build system by default

---

BUILD.bazel
BazelExtensions/xchammerconfig.bzl
BazelExtensions/xcode_configuration_provider.bzl
BazelExtensions/xcodeproject.bzl

The current API for XCHammer config doesn't provide a way to put
configuration adjacent to target definition.
This PR adds a provider to inject XCHammer Config onto Swift and Objc
targets.
It then injects these targets into the `xcode_project` rule via aspect
which is able to collect transitive target configuration.

Xcode target configuration aspect

---

BUILD.bazel
BazelExtensions/xcode_configuration_provider.bzl
BazelExtensions/xcodeproject.bzl
Sources/XCHammer/Generator.swift
Sources/XCHammer/XcodeTarget.swift

Add an aspect to extract generated files from the Bazel build graph.
The output of this aspect is fed into a rule, which then builds
generated files for Xcode.  Finally, the rule installs them into
bazel-genfiles locally.
Additionally:
- Fix issue around binary path
- Specify non-hermetic rules for install too

xcode_project - build generated files via aspect

---

Sources/XCHammer/ProcessIpa.swift
Sources/XCHammer/XcodeTarget.swift

In Swift 5, [`index(of:)`](https://developer.apple.com/documentation/swift/array/3126950-index) is deprecated and [`firstIndex(of:)`](https://developer.apple.com/documentation/swift/array/2994720-firstindex) is recommended instead.

Replace deprecated index(of:) with firstIndex(of:)

---

IntegrationTests/Goldmaster/SnapshotMe/XcodeBazel.xcodeproj/project.pbxproj
IntegrationTests/Goldmaster/Tailor/Tailor.xcodeproj/project.pbxproj
IntegrationTests/Goldmaster/Tailor/XcodeBazel.xcodeproj/project.pbxproj
IntegrationTests/Goldmaster/UrlGet/UrlGet.xcodeproj/project.pbxproj
IntegrationTests/Goldmaster/UrlGet/XcodeBazel.xcodeproj/project.pbxproj
IntegrationTests/Goldmaster/WorkspaceSource/WorkspaceSource.xcodeproj/project.pbxproj
IntegrationTests/Goldmaster/WorkspaceSource/XcodeBazel.xcodeproj/project.pbxproj
Sources/XCHammer/XcodeTarget.swift
Sources/XCHammer/main.swift

Some commands use underscores (such as `install_xcode_build_system`), but `process-ipa` uses a hyphen. This PR makes the format consistent.

Make process_ipa match formatting of other commands

---

Sources/XCHammer/Generator.swift
Sources/XCHammer/XcodeScheme.swift

When Xcode schemes are disabled, this PR drops the suffix. This makes it
easier to migrate over to Bazel.

Conditionally drop -Bazel suffix from schemes

---

third_party/repositories.bzl

This PR bumps the tulsi fork to allow us to better support arbitrary build configurations, e.g. "Profile"

Bump tulsi - no config validation

---

Sources/XCHammer/XCBuildSettings.swift

An empty identity is not valid when signing a binary for the product
type 'Application'.
Fixed by setting CODE_SIGNING_ALLOWED = NO

Fix "An empty identity is not valid" on XCBuild

---

IntegrationTests/run_tests.sh
Makefile
Sources/XCHammer/Generator.swift
Sources/XCHammer/XCBuildSettings.swift
Sources/XCHammer/XcodeTarget.swift
sample/UrlGet/BUILD.bazel
third_party/repositories.bzl

Adds the ability to generate only Xcode or Bazel targets
- Rename Bazel targets to Xcode targets
- Add only indexer targets to the project

Remove -Bazel suffix when generateXcodeSchemes=false

---

Sources/XCHammer/Generator.swift
Sources/XCHammer/XcodeScheme.swift
Sources/XCHammer/XcodeTarget.swift

Some extension types require a remote debuggable and different runtime
configuration. Simply put, at launch, this auto selects the executable.
This closely mirrors how Xcode sets up the schemes

Automatically add launch automatically substyle

---

.bazelrc
BUILD.bazel
README.md
Sources/XCHammer/XcodeTarget.swift
third_party/repositories.bzl
tools/BazelToolchain.xcconfig

This bumps tulsi to use the debug info prefix mapping setup by
`rules_swift` ( previously, we used another path for Pinterest internal
toolchain setup ).
By default, the variable is not set `HAMMER_USE_DEBUG_INFO_REMAPPING`
and is added to the README. In the future, this may be tured on, but is
left off if people want to use older swift releases

Support rules_swift debug info remapping feature

---

BazelExtensions/xcodeproject.bzl

In some situations, the __internal__.apple_binary ends up with an
XcodeProjectConfig instance. This PR works around this by removing the
suffix on the XCHammerConfig inside of the rule

Drop .__internal__.apple_binary suffix in config

---

Sources/XCHammer/XcodeTarget.swift

This fixes a bug using iOS frameworks in extensions for Pure Xcode
builds where the frameworks are filtered out.

Collect ios_framework dependencies

---

.bazelrc
WORKSPACE
XCHammerAssets/Hammer.bzl
third_party/repositories.bzl
tools/bazelwrapper

This PR updates XCHammer to build with Bazel 3.4.1 fixing misc updated
APIs.t  `tools/bazelwrapper` is still used to handle subbing of template
vars - it simply invokes `tools/bazelwrapper` It also includes a tulsi
bump to the latest for this support.

Update XCHammer to Bazel 3.4.1 with Bazelisk

---

BazelExtensions/xchammerconfig.bzl
BazelExtensions/xcode_configuration_provider.bzl
Makefile
Sources/XCHammer/Generator.swift
Sources/XCHammer/XCBuildSettings.swift
Sources/XCHammer/XcodeTarget.swift
XCHammerAssets/swiftc_stub.py
tools/bazelwrapper

First, it removes transitive module map collection. This is no longer
needed and produces a different result.
Next, It improves the handling of copts in general to adopt the calling
`expand_location` inside of the aspect. In PodToBUILD, we just landed a
series of changes to build the top 50 swift cocoapods. Like other usages
of building mixed module swift libs, it uses `$(execpath` to pass an
internal module map via fmodule-map-file=. The reference Tulsi PR
resides here: https://github.com/bazelbuild/tulsi/pull/157 and I bumped
XCHammer to include this here
https://github.com/pinterest/xchammer/pull/243
Finally, it adds installation of swiftmodules and corresponding include
paths. This makes it easy for sourcekit to pick them up. Additionally, it
creates a swift stub to prevent Xcode from …

Improve handling of Swift under Bazel builds

---

BazelExtensions/xcode_configuration_provider.bzl
BazelExtensions/xcodeproject.bzl

Under the latest Bazel + Rules apple the following changes happened.
1: different naming of test bundles this requires updating of the
`__internal__` binary replacement
2: propgation of transitive headermaps

Misc fixes for latest Bazel + rules_apple

---

third_party/repositories.bzl

We've hit a few other issues when upgrading to Bazel 3.4.1 that seemed
intermittent before.
Under XCBuild it will conditionally install the XCTest dylibs and
other dylibs only if the bundle has changed. Under XCBuild the
result is that the dylibs are stripped out of the bundle from the
previous build. This change also sync bundles directly to the output
location if they exist.
Please find more info in the linked commit

Bump Tulsi to HEAD

---

Sources/XCHammer/Monoids.swift
Sources/XCHammer/XCBuildSettings.swift
Sources/XCHammer/XcodeTarget.swift

On my encatation of macOS Catalina, XCBuild, and Xcode 11, the simulator
intermittently fails with the error "Could not attach to pid:"
It turns out that there's 2 symptoms
1: the binary doesn't launch
2: lldb fails to attach w/o get-task-allow
For now, the workaround allows XCBuild to code sign if needed. Longer
term, we shouldn't really need this but folks often have to add the
setting manually.
Additionally, streamlines some of the keys.

Stop gap for "Could not attach to pid:"

---

Docs/XCHammerOverview.md

It shouldn't be a sub item of this header

Docs: Move introduction out of Table of Contents

---

BazelExtensions/xcodeproject.bzl

Fixes https://github.com/pinterest/xchammer/issues/241
I think the issue could be reproduced if the `xcode_project` rule is placed somewhere NOT in the top level of the bazel workspace.
All samples in this repo have the `BUILD.bazel` files next to the `WORKSPACE`, and I think that may be why the issue does not arise on CI.

Correct output path for the ditto command

---

BazelExtensions/xcodeproject.bzl

The directory inside of `execroot` is subject to change. It's possible
that running bazel after generating the Xcode project puts the wrong
material there.

symlink `external` to installroot external dir

---

BUILD.bazel
README.md
tools/XCHammerXcodeRunscript.sh

By default this is set to `fastbuild` and debug info isn't set or
working. This PR uses existing config systems to set the
`compilation_mode`
Additionally document current config possibilities which don't really
handle this by default.
After running into this in XCHammer it's pretty clear to me that we
should have a sensible default to set the `compilation_mode` by default.
Perhaps a followup could consider adding defaults. I realized we don't
have this issue in the test sample because it sets the default
`compilation_mode` to `dbg` in the `.bazelrc`

Add `compilation_mode` into XCHammer's own xcodeproj

---

.bazelrc
Docs/XCHammerFAQ.md

When doing a build from the CLI it should align with what Xcode is doing
This is also required to make sure `xchammer_dev_repo` points to the
right place
Additionally, I've made a few improvements and added better guidance on
debugging

Align CLI flags with Xcode

---

sample/Frankenstein/tools/bazelwrapper
sample/SnapshotMe/tools/bazelwrapper
sample/Tailor/tools/bazelwrapper
sample/UrlGet/tools/bazelwrapper
sample/WorkspaceSource/tools/bazelwrapper

Under some newer versions of bash (perhaps macOS-specific?), we should
account for errors returned by dirname(1). Also pass `-P` to pwd(1).

Safer SCRIPTPATH formation

---

README.md

This is no longer relevant now that we use GitHub Actions for CI.

Remove the Travis CI badge

---

Sources/XCHammer/Generator.swift

Saw some error with XCode version 12.3.0. 
Recent error is  "Fatal error: Can't write temp objc stub: file Sources/XCHammer/Generator.swift, line 505", however without file path.
This pull request to print file path to help troubleshooting issue during generating.

Print path in writing file error [Generator.swift]

---

.bazelrc
WORKSPACE
third_party/repositories.bzl

This represents the minimal set of changes to get this project through
the upstream Bazel project's ObjcProvider migration:
https://github.com/bazelbuild/bazel/issues/10674
In addition to updating our direct WORKSPACE dependencies, it also bumps
the commit reference to our (quite stale) Tulsi fork that now contains
these cherry-picked upstream commits:
Branch: xchammer-0.28.1
- https://github.com/pinterest/tulsi/commit/432cdb64c0ebf3bae73dda598147ac3dc4224b54
- https://github.com/pinterest/tulsi/commit/62cfb95c68a2842a99c395d1f12715928eccfc3e
- https://github.com/pinterest/tulsi/commit/131e87bbd5d5aab43a3c98d95d92749c68f35f73
Branch: xchammer-3.4.1
- https://github.com/pinterest/tulsi/commit/3d4f37a67e22dcaa5a9daf212ee11a874676ad7f
- …

Support Bazel ObjcProvider compile_info migration

---

BazelExtensions/xcode_configuration_provider.bzl

This supports the ObjcProvider compilation_context migration. We
continue to fall back on objc.header when CcInfo is not available, but
this will go away once we require Bazel 4.x.

Fetch headers from CcInfo when available

---

third_party/repositories.bzl

This was caused by a local patch we have in our Tulsi fork, so I've
patch it there:
https://github.com/pinterest/tulsi/commit/d9f7da58ff7a620e64d695baa2179c3598333bf7

Address "'depset' is not iterable" in Tulsi

---

Docs/XCHammerFAQ.md
Docs/XCHammerOverview.md

These were identified in #254, but I'm extracting them to a simple diff
that only makes these fixes.
Co-authored-by: Andres Cecilia Luque <a.cecilia.luque@gmail.com>

Fix up some broken documentation links

---

sample/Frankenstein/WORKSPACE
sample/Frankenstein/tools/bazelwrapper
sample/SnapshotMe/WORKSPACE
sample/SnapshotMe/tools/bazelwrapper
sample/Tailor/WORKSPACE
sample/Tailor/tools/bazelwrapper
sample/UrlGet/.bazelrc
sample/UrlGet/Vendor/GoogleAppIndexing/BUILD
sample/UrlGet/WORKSPACE
sample/UrlGet/ios-app/BUILD
sample/UrlGet/tools/bazelwrapper
sample/WorkspaceSource/WORKSPACE
sample/WorkspaceSource/tools/bazelwrapper

i.e., **make run_swift** should work now, which previously would fail.
The integration test(make test) requires more changes, but only a few errors now :)
```
The following build commands failed:
Ld /Users/lma/Library/Developer/Xcode/DerivedData/UrlGet-hgpbgbnmkatzrbcfjhuuwfdjsmxh/Build/Intermediates.noindex/UrlGet.build/Debug-iphonesimulator/ios-app.build/Objects-normal/x86_64/Binary/ios-app normal x86_64 (in target 'ios-app' from project 'UrlGet')
Ld /Users/lma/Library/Developer/Xcode/DerivedData/UrlGet-hgpbgbnmkatzrbcfjhuuwfdjsmxh/Build/Intermediates.noindex/UrlGet.build/Debug-iphonesimulator/ios-app.build/Objects-normal/i386/Binary/ios-app normal i386 (in target 'ios-app' from project 'UrlGet')
Ld /Users/lma/Library/Developer/Xcode/DerivedData/UrlGet-hgpbgbnmkatzrbcfjhuuwfdjsmxh/Build/ …
```

Update dependencies of sample tests so most of them are able to run 

---

third_party/repositories.bzl

- bump tulsi version
- add variable `PINTEREST_TULSI_COMMIT` to reuse same commit across all uses of Tulsi, as the mismatch is the source of current errors from what I can tell

bump tulsi, and use the same version in both locations
