export_tulsi_aspect_dir.sh
This `xcodebuild` is very noisy. How do you feel about making `-quiet` the default?
=> Build Tulsi with -quiet

Package.swift
Bump to the tip of master as of today for relevant fixes and
improvements by @yonaskolb @kastiglione @jerrymarino
=> Bump XcodeGen

Sources/XCHammer/XcodeTarget.swift
Recently, XcodeGen gained the ability to copy files for headers. This
behavior doesn't really add value for XCHammer and slows down project
gen for some cases by ~ 1 order of mangitude.
Fixes #58
=> Disable header copying

Sources/XCHammer/XcodeTargetMap.swift
=> Resolve deprecated String API use

WORKSPACE, sample/Frankenstein/WORKSPACE, sample/Frankenstein/tools/bazelwrapper, sample/Tailor/WORKSPACE, sample/Tailor/tools/bazelwrapper, sample/UrlGet/WORKSPACE, sample/UrlGet/tools/bazelwrapper, third_party/repositories.bzl, tools/bazelwrapper
Package.swift (xcodegen, tulsi updates)
- Update Tulsi, XcodeGen in repositories.bzl
- Update bazelwrapper to build with 0.18.0
- Update rules_apple to 0.8.0
- Update rules_swift to 0.3.1
=> Update bazel and rules dependencies to latest

Sources/XCHammer/XCBuildSettings.swift, Sources/XCHammer/XcodeTarget.swift
Prior, we expected this to be set by `SettingsPresests`.
=> Compose deployment target settings on Bazel Target

.gitignore, BUILD.bazel, Makefile, Sources/XCHammer/Generator.swift, Sources/XCHammer/XCHammerLogger.swift, Sources/XCHammer/main.swift, tools/instrumentation_helpers/instrumentor.py, tools/instrumentation_helpers/statsd_post_build_action.py, tools/instrumentation_helpers/statsd_post_build_action.sh, tools/instrumentation_helpers/statsd_post_generate_action.py, tools/instrumentation_helpers/statsd_pre_build_action.sh, tools/xchammerconfig.bzl
This PR contains several bits of statsd logging infrastructure.
In summary, it has the ability to log generation time and build time.
=> Several statsd logging bits

Sources/XCHammer/Generator.swift
=> Add test targets to `test` scheme action

tools/instrumentation_helpers/instrumentor.py
- Memoize system_profiler
- lift work out of for loop
=> Prevent redundant calls in instrumentor.py

Sources/XCHammer/XcodeTarget.swift
Make build settings idempotnent to prevent unnecessary rebuilds accross
project generation.
It sorts all known inputs to Xcode target build settings including
compiler flags and linker flags.
Future work should include adding tests around this.
=> Make Xcode Target build settings idempotent

Sources/XCHammer/XcodeTarget.swift, sample/UrlGet/ios-app/BUILD
- The project had the wrong rule for some reason
- There was a few missing conditionals
=> Fix issues with ios_ui_test

Sources/XCHammer/XcodeTarget.swift
Start adding: 
https://docs.bazel.build/versions/master/be/make-variables.html
Additionally remove extra headermap propagation
=> Better headermap and make variable support

Sources/XCHammer/Generator.swift
Locally, `String.hashValue` produces a different output
Fixes #184
=> [Catalina] Use dbjhash instead of String.hashValue

third_party/repositories.bzl
=> Update Tulsi to write Aspect standard error

Sources/XCHammer/Generator.swift, Sources/XCHammer/XcodeTarget.swift, Sources/XCHammer/XcodeTargetMap.swift
- fix genstatus regression
- include only for specified labels
- filter dependencies, resources
- fix label names when specifying generate transitive
=> Misc fixes and improvements for focused projects

BUILD.bazel, BazelExtensions/xcode_configuration_provider.bzl, BazelExtensions/xcodeproject.bzl, Makefile, Sources/XCHammer/Generator.swift, Sources/XCHammer/XcodeTarget.swift
This approach has several advantages and fewer tradeoffs than doing it
post-build or during generation time
=> Install genfiles during Bazel builds

Sources/XCHammer/XcodeTarget.swift
A previous commit eagerly stripped this out
=> Fix linker opts for workspace mode

Sources/XCHammer/XcodeTarget.swift
This works around the fact that we derive linker invocations from an
ad-hoc synthetic dependency graph.
=> Reject headermap deps from linker invocations

Sources/XCHammer/XcodeBuildSystemInstaller.swift, WORKSPACE
Additionally, add pointer to /var/log/install.log for failed installs.
=> Bump XCBuildkit to latest

third_party/repositories.bzl
Mainly for this commit
https://github.com/yonaskolb/XcodeGen/commit/1e3f93a8593dae08c3db6ee8cecc0bf3b83cc9f2
Updates related deps
=> Bump XcodeGen to HEAD

Docs/PinterestFocusedXcodeProjects.md, Docs/XCHammerFAQ.md, Docs/XCHammerOverview.md, README.md
Adds a small overview of XCHammer including the aspects, rule, and
command line interface
Additionally include a segment about common problems and solutions
=> Write a quick overview of XCHammer

Sources/XCHammer/XcodeTarget.swift
Adding in iMessage into XcodeTarget.swift
=> Add imessage to XcodeTarget

Docs/BazelForiOSDevelopers.md
Hello XCHammer maintainers team. I've been learning about Bazel this week and found your document super informative.
While reading through it, I found some very minor things that could be tweaked, so I thought I'd open a PR for that.
My intent here is to help make a useful document even more accessible, I hope I'm not coming across as a nitpicky contributor.
I made every change in a dedicated commit, so if there's something you'd rather not integrate, it can be easily dropped.
Thanks for the work you put into crafting this document, XCHammer, and your contributions to the community.
=> Minor tweaks in the Bazel for iOS developers docs

third_party/repositories.bzl
Fixes https://github.com/pinterest/xchammer/issues/257
=> Bump SwiftShell to 5.1 to fix Xcode 12 building issue

Docs/XCHammerFAQ.md, README.md
Now that this feature is well, supported add better docs on it.
Additionally simplify the README
=> Instructions for Xcode development of Bazel rules

BazelExtensions/xcode_configuration_provider.bzl
This fixes the logic introduced in #281.
=> Improve objc header detection

third_party/repositories.bzl
- https://github.com/pinterest/tulsi/commit/70f18391fda3feef42179442a30505401aa2a774
- https://github.com/pinterest/tulsi/commit/e8431a1f4f309e2271e8a0f1f5cd57e4c881893b
- https://github.com/pinterest/tulsi/commit/c180639af0a20779610b4cbedd47f69849479366
=> Update pinterest/tulsi fork to c180639a

third_party/repositories.bzl
landed in tulsi fork, ready to land here
=> tulsi: use a commit including the updated aspects

third_party/repositories.bzl
update tulsi to latest to include deprecation of python2 and switch to python3
https://github.com/pinterest/tulsi/commit/9fb0df4ca7838cf794c2891869385b7e49860544
=> update tulsi to latest to include deprecation of python2 and switch to python3
